name: iot_attack_cl_ids
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9,<3.11
  - pip
  - pip:
      - torch>=1.13.1,<2.2
      - numpy>=1.23
      - pandas>=1.5
      - scikit-learn>=1.0
      - tqdm>=4.64
      - wandb>=0.15
      - matplotlib>=3.5
      - seaborn>=0.12
      - scipy>=1.8
      - typing-extensions>=4.0
